unknownProperty: true

builder:
  track: dev

labels:
  app: ziplinee-ci-builder
  team: ziplinee-team
  language: golang

version:
  semver:
    major: 1
    minor: 2
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: main

env:
  VAR_A: Greetings
  VAR_B: World

# automatically executed stages on a push to the repository
stages:
  build:
    image: golang:1.8.0-alpine
    workDir: /go/src/github.com/ziplineeci/ziplinee-ci-builder
    commands:
    - go test -v ./...
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o
      ./publish/ziplinee-ci-builder .

  bake:
    image: docker:17.03.0-ce
    shell: /bin/bash
    commands:
    - cp Dockerfile ./publish
    - docker build -t ziplinee-ci-builder ./publish

  set-build-status:
    image: extensions/github-status:0.0.2
    when: server == 'ziplinee'

  push-to-docker-hub:
    image: docker:17.03.0-ce
    commands:
    - docker login --username=${ZIPLINEE_DOCKER_HUB_USERNAME}
      --password='${ZIPLINEE_DOCKER_HUB_PASSWORD}'
    - docker push ziplinee/${ZIPLINEE_LABEL_APP}:${ZIPLINEE_BUILD_VERSION}
    when: status == 'succeeded' && branch == 'main'

  slack-notify:
    image: docker:17.03.0-ce
    env:
      SOME_ENVIRONMENT_VAR: "some value with spaces"
    commands:
    - 'curl -X POST --data-urlencode ''payload={"channel": "#build-status",
      "username": "ziplinee-ci-builder", "text": "Build
      ${ZIPLINEE_BUILD_VERSION} for ${ZIPLINEE_LABEL_APP} has failed!"}''
      ${ZIPLINEE_SLACK_WEBHOOK}'
    when: status == 'failed' || branch == 'main'
    unknownProperty1: value1
    unknownProperty2: value2
    unknownProperty3:
    - supported1
    - supported2

  test-alpha-version:
    image: extensions/gke:${ZIPLINEE_BUILD_VERSION}
    credentials: gke-tooling
    app: gke
    namespace: ziplinee
    visibility: private
    container:
      repository: extensions
      name: gke
      tag: alpha
    cpu:
      request: 100m
      limit: 100m
    memory:
      request: 256Mi
      limit: 256Mi
    dryrun: true

# releases are automatically triggered from stages or manually from gui, cli or slack
releases:
  docker-hub:
    stages:
      push-image:
        image: extensions/push-to-docker-registry:dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:stable
        action: tag
        container: gke
        repositories:
        - extensions
        tags:
        - beta

  development:
    stages:
      deploy:
        image: extensions/deploy-to-kubernetes-engine:dev

  staging:
    stages:
      deploy:
        image: extensions/gke:beta
        volumemounts:
        - name: client-certs
          mountpath: /cockroach-certs
          volume:
            secret:
              secretName: ziplinee.client.ziplinee
              items:
              - key: key
                path: key
                mode: 600
                enabled: true
              - key: cert
                path: cert

  production:
    actions:
    - name: deploy-canary
    - name: rollback-canary
    - name: deploy-stable

    clone: true
    stages:
      deploy:
        image: extensions/deploy-to-kubernetes-engine:stable

      create-release-notes:
        image: extensions/create-release-notes-from-changelog:stable

  tooling:
